version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dsm_postgres_dev
    environment:
      POSTGRES_USER: dsm_user
      POSTGRES_PASSWORD: dsm_password # Consider using secrets or env vars for real dev
      POSTGRES_DB: dsm_dev_db
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dsm_user -d dsm_dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local